def coverage(options):
    return """
# This is a managed file generated by Projen. To edit, change the project template.
# .coveragerc
[paths]
source =
    "{name}/"
    "*/site-packages"
[run]
branch = true
[report]
fail_under = 70
show_missing = true
omit = 
    tests/
    {name}/cli/cli.py
    */__init__.py
  """.format(
        name=options["name"].replace("-", "_")
    )